### PR TITLE
Add Xcode 7.3 compatibility

### PR DESCRIPTION
**Pull request by mttcrsp**

### CODE REVIEW

**Comment by ebaker355** [comment]
Actually, that UUID C4A681B0-4A26-480E-93EC-1218098B9AA0 is already in the Info.plist file. I think the one for Xcode 7.3 is ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C

**Comment by mttcrsp** [comment]
Sorry, updated.

**Comment by mttcrsp** [comment]
Sorry, updated. I reordered all of the UUIDs and added references to the corresponding Xcode version so that it won't happen again.

**Comment by ebaker355** [comment]
:+1:

**Comment by liscio** [comment]
This looks good to me. Thanks for the patch!

**Pull request merged**
